### ISSUE TITLE
Using two (or more) ordering columns

### ISSUE THREAD

**Issue by djonatanb** [ADmad/cakephp-sequence#17]
Hey, thanks for your work on this

I have a case where I wanted to keep two columns storing the order. 
Is there anyway to accomplish that with the plugin? maybe a workaround? 

The case is like a voting system with two phases. I have an order for the first phase and an order for the second phase, they can both be edited.

**Comment by ADmad** [comment]
The plugin/behavior doesn't support multiple ordering fields. 

For your particular use case since your probably won't need to maintain 2 orders simultaneously once the first phase is done you can copy the values of order field to another field or reconfigure the behavior at runtime to using another field for second phase.

**Comment by djonatanb** [comment]
Yes, reconfiguring at runtime should be enough. Will try to do that. Thanks
