### ISSUE TITLE
Randomly ordered Entities

### ISSUE THREAD

**Issue by anvyst** [ADmad/cakephp-sequence#28]
I've started using this plugin, when users already had `order` field in place within `qobo/cakephp-survey` plugin.

As a result, some of the entities had following order sequence within defined survey questions scope:
```php
[
  'question_1' => 1,
  'question_2' => 2, 
  'question_3' => 5,
];
```

The UI has a wrapper for `moveUp()` and `moveDown()` methods of the behaviour, and everything works fine, but when the user has to swap `question_2` and `question_3`, the first one has to be clicked multiple times to reach `4 <-> 5` swap. 

Moving `question_3` up, the user still has to click multiple times.

I could look into slightly changing `_movePosition()` method to look for closest neighbour entity (depending whether its up/down direction) and re-calculate its `position` fields, to get rid off possible gaps.

**Comment by ADmad** [comment]
The behavior is meant to work on sequential values hence the name :slightly_smiling_face:. A problem such as yours wouldn't arise if you start with "clean" data. You could just "fix" your data initially and set sequential values.

I don't really want to add unnecessary complexity to `_movePosition()` to cater to such edges cases. But if the fix is simple I am willing to consider it.

**Comment by anvyst** [comment]
@ADmad I've tried a number of ways to refactor `_movePosition()` to get neighbour entities - it blew up code complexity, so I guess we can close this issue, as `setOrder()` does it better :)

**Comment by ADmad** [comment]
Okay
